# Generated by Django 5.2.16 on 2026-09-19 10:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_recording_concurrent_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='active_participant_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='last_activity_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='room',
            name='last_empty_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='lifecycle_status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('instant', 'Instant meeting'), ('scheduled', 'Scheduled meeting')], db_index=True, default='instant', max_length=20),
        ),
        migrations.CreateModel(
            name='ScheduledMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('topic', models.CharField(max_length=500)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=64)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('finished', 'Finished')], db_index=True, default='scheduled', max_length=20)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organized_meetings', to=settings.AUTH_USER_MODEL)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_meeting', to='core.room')),
            ],
            options={
                'db_table': 'meet_scheduled_meeting',
                'ordering': ('starts_at',),
            },
        ),
        migrations.CreateModel(
            name='MeetingInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('email', models.EmailField(max_length=254)),
                ('is_organizer', models.BooleanField(default=False)),
                ('response_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], db_index=True, default='pending', max_length=20)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('initial_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_30m_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_10m_sent_at', models.DateTimeField(blank=True, null=True)),
                ('send_error', models.TextField(blank=True, default='')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.scheduledmeeting')),
            ],
            options={
                'db_table': 'meet_meeting_invitation',
                'indexes': [models.Index(fields=['response_status', 'reminder_30m_sent_at'], name='meet_meetin_respons_e2d85d_idx'), models.Index(fields=['response_status', 'reminder_10m_sent_at'], name='meet_meetin_respons_d44aeb_idx')],
                'constraints': [models.UniqueConstraint(fields=('meeting', 'email'), name='uniq_meeting_invitation_email')],
            },
        ),
    ]
