# Generated by Django 5.2.16 on 2026-09-20 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_scheduled_meetings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetinginvitation',
            options={'verbose_name': '会议邀请', 'verbose_name_plural': '会议邀请'},
        ),
        migrations.AlterModelOptions(
            name='scheduledmeeting',
            options={'ordering': ('starts_at',), 'verbose_name': '日程会议', 'verbose_name_plural': '日程会议'},
        ),
        migrations.AlterField(
            model_name='meetinginvitation',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='确认时间'),
        ),
        migrations.AlterField(
            model_name='meetinginvitation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='受邀邮箱'),
        ),
        migrations.AlterField(
            model_name='meetinginvitation',
            name='initial_email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='邀请邮件发送时间'),
        ),
        migrations.AlterField(
            model_name='meetinginvitation',
            name='is_organizer',
            field=models.BooleanField(default=False, verbose_name='是否主持人'),
        ),
        migrations.AlterField(
            model_name='meetinginvitation',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.scheduledmeeting', verbose_name='日程会议'),
        ),
        migrations.AlterField(
            model_name='meetinginvitation',
            name='reminder_10m_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='会前10分钟提醒时间'),
        ),
        migrations.AlterField(
            model_name='meetinginvitation',
            name='reminder_30m_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='会前30分钟提醒时间'),
        ),
        migrations.AlterField(
            model_name='meetinginvitation',
            name='response_status',
            field=models.CharField(choices=[('pending', '待确认'), ('accepted', '已确认')], db_index=True, default='pending', max_length=20, verbose_name='确认状态'),
        ),
        migrations.AlterField(
            model_name='meetinginvitation',
            name='send_error',
            field=models.TextField(blank=True, default='', verbose_name='邮件发送错误'),
        ),
        migrations.AlterField(
            model_name='meetinginvitation',
            name='token_digest',
            field=models.CharField(max_length=64, unique=True, verbose_name='确认令牌摘要'),
        ),
        migrations.AlterField(
            model_name='scheduledmeeting',
            name='ends_at',
            field=models.DateTimeField(db_index=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='scheduledmeeting',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organized_meetings', to=settings.AUTH_USER_MODEL, verbose_name='主持人'),
        ),
        migrations.AlterField(
            model_name='scheduledmeeting',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_meeting', to='core.room', verbose_name='会议室'),
        ),
        migrations.AlterField(
            model_name='scheduledmeeting',
            name='starts_at',
            field=models.DateTimeField(db_index=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='scheduledmeeting',
            name='status',
            field=models.CharField(choices=[('scheduled', '已预约'), ('cancelled', '已取消'), ('finished', '已结束')], db_index=True, default='scheduled', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='scheduledmeeting',
            name='timezone',
            field=models.CharField(default='Asia/Shanghai', max_length=64, verbose_name='时区'),
        ),
        migrations.AlterField(
            model_name='scheduledmeeting',
            name='topic',
            field=models.CharField(max_length=500, verbose_name='会议主题'),
        ),
    ]
